class StateDataService
  class << self
    def get_state(state_code)
      STATES_DATA[state_code.upcase]
    end

    def all_states
      STATES_DATA
    end

    def major_states_with_counts
      major_states = %w[
        CA NY TX FL MA IL PA OH MI NC VA WA GA NJ MD WI MN AZ IN TN
        MO AL KY CO SC IA OR KS AR MS LA NV UT NM CT OK NE WV ID NH
        ME HI RI DE MT WY SD ND VT AK DC
      ]

      major_states.map do |state_code|
        state_data = get_state(state_code)
        next unless state_data

        # 4年制・非営利大学のみカウント
        college_count = Condition.where(state: state_code)
                                 .where(privateorpublic: [ "私立", "州立" ])
                                 .where("carnegie_basic >= 15")
                                 .count

        state_data.merge(
          code: state_code,
          college_count: college_count
        )
      end.compact.sort_by { |state| -state[:college_count] }
    end
  end

  STATES_DATA = {
    "AL" => {
      name: "アラバマ州",
      english_name: "Alabama",
      nickname: "ハート・オブ・ディキシー",
      capital: "モンゴメリー",
      largest_city: "ハンツビル",
      population: "約510万人",
      area: "135,767 km²",
      climate: "亜熱帯湿潤気候",
      average_temp: "年間平均気温：16-20°C",
      cost_of_living: "低い（全米平均の85-90%）",
      economy: "自動車製造、航空宇宙、農業、軍事",
      famous_for: "公民権運動の歴史、NASAマーシャル宇宙飛行センター、カレッジフットボール",
      education_highlights: "Auburn大学、University of Alabama、UABなど",
      international_students: "手頃な学費とフレンドリーな環境",
      job_opportunities: "航空宇宙、自動車製造、ヘルスケア分野で成長中",
      description: "アメリカ南部の歴史と文化が色濃く残る州。公民権運動の発祥地として知られ、キング牧師が活動した歴史的な場所が点在する。近年はハンツビルを中心に航空宇宙産業が急成長しており、NASAやボーイングなどが拠点を構える。生活費が全米でも最も低い水準にあり、温暖な気候と南部特有のホスピタリティが留学生を温かく迎え入れる。"
    },
    "AK" => {
      name: "アラスカ州",
      english_name: "Alaska",
      nickname: "ラスト・フロンティア",
      capital: "ジュノー",
      largest_city: "アンカレッジ",
      population: "約73万人",
      area: "1,723,337 km²",
      climate: "亜寒帯～極地気候",
      average_temp: "年間平均気温：-3-5°C",
      cost_of_living: "高い（全米平均の125-135%）",
      economy: "石油・天然ガス、漁業、観光、軍事",
      famous_for: "オーロラ、デナリ（北米最高峰）、野生動物、氷河",
      education_highlights: "University of Alaska系列校",
      international_students: "ユニークな自然環境での学習機会",
      job_opportunities: "エネルギー産業、漁業、観光、環境科学分野",
      description: "アメリカ最大かつ最北の州で、手つかずの大自然が広がる「最後のフロンティア」。世界有数の石油・天然ガス資源を持ち、エネルギー産業が経済の柱となっている。冬にはオーロラ、夏には白夜を体験できる唯一無二の環境で、海洋生物学や環境科学を学ぶには最適の場所。少人数制の大学が多く、教授との距離が近いアットホームな学習環境が特徴。"
    },
    "AZ" => {
      name: "アリゾナ州",
      english_name: "Arizona",
      nickname: "グランドキャニオンステート",
      capital: "フェニックス",
      largest_city: "フェニックス",
      population: "約730万人",
      area: "295,234 km²",
      climate: "砂漠気候～半乾燥気候",
      average_temp: "年間平均気温：18-25°C",
      cost_of_living: "中程度（全米平均の95-105%）",
      economy: "テクノロジー、航空宇宙、製造業、観光",
      famous_for: "グランドキャニオン、砂漠の風景、先住民文化",
      education_highlights: "Arizona State University、University of Arizona等",
      international_students: "年間300日以上の晴天と成長するテック産業",
      job_opportunities: "半導体製造、航空宇宙、再生可能エネルギー分野で急成長",
      description: "世界遺産グランドキャニオンを擁する砂漠の州。年間300日以上の晴天に恵まれ、温暖で乾燥した気候が特徴。近年はフェニックス都市圏を中心にテクノロジー企業の進出が相次ぎ、台湾TSMCの大規模半導体工場建設など、製造業の新たな拠点として注目を集めている。Arizona State Universityは全米最大規模の学生数を誇り、革新的なオンライン教育でも知られる。"
    },
    "AR" => {
      name: "アーカンソー州",
      english_name: "Arkansas",
      nickname: "ナチュラルステート",
      capital: "リトルロック",
      largest_city: "リトルロック",
      population: "約305万人",
      area: "137,732 km²",
      climate: "亜熱帯湿潤気候",
      average_temp: "年間平均気温：14-18°C",
      cost_of_living: "低い（全米平均の80-90%）",
      economy: "農業、小売、物流、食品加工",
      famous_for: "ウォルマート本社、ホットスプリングス国立公園、自然の美しさ",
      education_highlights: "University of Arkansas、Hendrix College等",
      international_students: "非常に手頃な学費と生活費",
      job_opportunities: "小売、物流、農業テクノロジー分野",
      description: "「自然の州」の愛称にふさわしく、オザーク山脈や多くの湖、温泉が点在する美しい州。世界最大の小売企業ウォルマートと食品大手タイソンフーズの本社があり、ビジネススクールでのインターンシップ機会が豊富。生活費と学費が全米最低水準で、留学費用を抑えたい学生に最適。南部特有の温かいコミュニティと四季折々の自然が、充実した留学生活を約束する。"
    },
    "CA" => {
      name: "カリフォルニア州",
      english_name: "California",
      nickname: "ゴールデンステート",
      capital: "サクラメント",
      largest_city: "ロサンゼルス",
      population: "約3,900万人",
      area: "423,970 km²",
      climate: "地中海性気候～砂漠気候",
      average_temp: "年間平均気温：15-22°C",
      cost_of_living: "高い（全米平均の130-150%）",
      economy: "テクノロジー、エンターテインメント、農業、観光",
      famous_for: "シリコンバレー、ハリウッド、ディズニーランド、ゴールデンゲートブリッジ",
      education_highlights: "Stanford、UC Berkeley、Caltech、UCLA等の世界トップ校",
      international_students: "全米最多の留学生数、多様な文化環境",
      job_opportunities: "テック、エンターテインメント、バイオテクノロジーで無限の機会",
      description: "アメリカ最大の人口と経済規模を誇る「ゴールデンステート」。シリコンバレーには世界のテック企業が集結し、Apple、Google、Meta、Netflixなどがイノベーションを生み出し続けている。UC系列10校とCal State系列23校、さらにStanford、Caltechといった私立名門校まで、あらゆるレベル・分野の教育機会が揃う。温暖な気候、太平洋のビーチ、多様な文化背景を持つコミュニティが、世界中から学生を引きつけている。"
    },
    "CO" => {
      name: "コロラド州",
      english_name: "Colorado",
      nickname: "センテニアルステート",
      capital: "デンバー",
      largest_city: "デンバー",
      population: "約580万人",
      area: "269,601 km²",
      climate: "半乾燥気候～高山気候",
      average_temp: "年間平均気温：7-12°C",
      cost_of_living: "高い（全米平均の105-120%）",
      economy: "テクノロジー、航空宇宙、観光、エネルギー",
      famous_for: "ロッキー山脈、スキーリゾート、アウトドアライフスタイル",
      education_highlights: "University of Colorado、Colorado School of Mines等",
      international_students: "アウトドア好きに最適な環境",
      job_opportunities: "テクノロジー、再生可能エネルギー、航空宇宙分野で成長中",
      description: "ロッキー山脈の麓に広がる自然とテクノロジーが融合する州。デンバー都市圏は「マウンテン・シリコンバレー」とも呼ばれ、多くのテック企業がオフィスを構える。冬はスキー、夏はハイキングやキャンプと、年間を通じてアウトドアアクティビティを楽しめる環境が最大の魅力。Colorado School of Minesは鉱業・エネルギー工学で世界トップクラス、University of Coloradoは宇宙科学研究で名高い。"
    },
    "CT" => {
      name: "コネチカット州",
      english_name: "Connecticut",
      nickname: "コンスティテューションステート",
      capital: "ハートフォード",
      largest_city: "ブリッジポート",
      population: "約360万人",
      area: "14,357 km²",
      climate: "湿潤大陸性気候",
      average_temp: "年間平均気温：8-12°C",
      cost_of_living: "高い（全米平均の115-130%）",
      economy: "金融、保険、製造業、ヘルスケア",
      famous_for: "イェール大学、保険業の中心地、美しいニューイングランドの街並み",
      education_highlights: "Yale University、University of Connecticut、Wesleyan等",
      international_students: "ニューヨークとボストンの中間という好立地",
      job_opportunities: "金融、保険、ヘルスケア、バイオテクノロジー分野",
      description: "ニューイングランド地方の豊かな歴史と文化が息づく小さな州。世界最高峰の大学イェールを擁し、学術研究の中心地として名高い。ハートフォードは「保険の首都」として知られ、多くの保険会社が本社を置く。ニューヨークまで電車で約2時間、ボストンまで約1.5時間という立地で、週末には両大都市へのアクセスも容易。四季折々の美しい自然と、歴史的な街並みが魅力。"
    },
    "DE" => {
      name: "デラウェア州",
      english_name: "Delaware",
      nickname: "ファーストステート",
      capital: "ドーバー",
      largest_city: "ウィルミントン",
      population: "約100万人",
      area: "6,446 km²",
      climate: "湿潤亜熱帯気候",
      average_temp: "年間平均気温：11-14°C",
      cost_of_living: "中程度（全米平均の100-110%）",
      economy: "金融、化学、製薬、企業サービス",
      famous_for: "法人税の優遇措置、デュポン発祥の地、消費税なし",
      education_highlights: "University of Delaware等",
      international_students: "小規模ながら質の高い教育環境",
      job_opportunities: "金融、化学、製薬分野",
      description: "アメリカ合衆国憲法を最初に批准した「ファーストステート」。面積は全米で2番目に小さいが、企業に有利な法制度により、フォーチュン500企業の60%以上がここに法人登記している。化学大手デュポンの発祥地であり、現在も化学・製薬産業が盛ん。消費税がないため、買い物客が近隣州から訪れることも多い。フィラデルフィアやボルチモアへのアクセスが良く、大都市の利便性と小さな州の親密さを両立。"
    },
    "FL" => {
      name: "フロリダ州",
      english_name: "Florida",
      nickname: "サンシャインステート",
      capital: "タラハシー",
      largest_city: "ジャクソンビル",
      population: "約2,200万人",
      area: "170,312 km²",
      climate: "亜熱帯～熱帯気候",
      average_temp: "年間平均気温：20-26°C",
      cost_of_living: "中程度（全米平均の100-115%）",
      economy: "観光業、航空宇宙、国際貿易、農業、ヘルスケア",
      famous_for: "ディズニーワールド、マイアミビーチ、ケネディ宇宙センター、エバーグレーズ",
      education_highlights: "University of Florida、University of Miami、Florida State等",
      international_students: "年中温暖な気候とラテン文化の影響",
      job_opportunities: "観光、国際ビジネス、航空宇宙、ヘルスケア分野",
      description: "年間を通じて温暖な「サンシャインステート」は、全米で3番目に人口が多い州。マイアミはラテンアメリカへのゲートウェイとして、国際ビジネスとスペイン語が日常的に飛び交う多文化都市。ケネディ宇宙センターではNASAの打ち上げを間近で見学でき、航空宇宙工学を志す学生に人気。州所得税がないため、卒業後の就職先としても魅力的。ビーチ、テーマパーク、野生動物など、勉強の息抜きに事欠かない環境。"
    },
    "GA" => {
      name: "ジョージア州",
      english_name: "Georgia",
      nickname: "ピーチステート",
      capital: "アトランタ",
      largest_city: "アトランタ",
      population: "約1,080万人",
      area: "153,910 km²",
      climate: "亜熱帯湿潤気候",
      average_temp: "年間平均気温：16-20°C",
      cost_of_living: "中程度（全米平均の90-100%）",
      economy: "物流、映画産業、テクノロジー、農業、金融",
      famous_for: "CNN本社、コカ・コーラ発祥地、「南部のハリウッド」",
      education_highlights: "Georgia Tech、Emory University、University of Georgia等",
      international_students: "成長するテック・映画産業と多様な文化",
      job_opportunities: "テクノロジー、映画・メディア、物流、ヘルスケア分野",
      description: "アメリカ南東部の経済・文化の中心地。アトランタは世界最大級のハブ空港を持ち、コカ・コーラ、デルタ航空、UPSなど多くの大企業本社が集まる。近年は「南部のハリウッド」として映画・TV産業が急成長し、マーベル映画やNetflixドラマの多くがここで撮影される。Georgia Techは工学・コンピュータサイエンスで全米トップ10に入る名門。温暖な気候と手頃な生活費、南部特有のホスピタリティが魅力。"
    },
    "HI" => {
      name: "ハワイ州",
      english_name: "Hawaii",
      nickname: "アロハステート",
      capital: "ホノルル",
      largest_city: "ホノルル",
      population: "約145万人",
      area: "28,313 km²",
      climate: "熱帯気候",
      average_temp: "年間平均気温：23-27°C",
      cost_of_living: "非常に高い（全米平均の150-180%）",
      economy: "観光業、軍事、農業、再生可能エネルギー",
      famous_for: "美しいビーチ、火山、フラダンス、多文化社会",
      education_highlights: "University of Hawaii系列校",
      international_students: "太平洋の文化的交差点、アジアへの近さ",
      job_opportunities: "観光、海洋科学、再生可能エネルギー、軍事関連",
      description: "太平洋に浮かぶ楽園の島々からなる唯一の州。アジア、ポリネシア、アメリカ本土の文化が融合した独自の「アロハ・スピリット」が根付く。海洋生物学、火山学、再生可能エネルギー研究では世界をリードし、天文台を擁するマウナケアでの宇宙観測も盛ん。日本からの距離が近く、日本語が通じる場所も多い。生活費は高いが、年中温暖な気候と美しい自然、リラックスしたライフスタイルは他州では味わえない。"
    },
    "ID" => {
      name: "アイダホ州",
      english_name: "Idaho",
      nickname: "ジェムステート",
      capital: "ボイシ",
      largest_city: "ボイシ",
      population: "約190万人",
      area: "216,443 km²",
      climate: "半乾燥気候～高山気候",
      average_temp: "年間平均気温：6-12°C",
      cost_of_living: "低い（全米平均の90-100%）",
      economy: "農業、テクノロジー、製造業、観光",
      famous_for: "ポテト（じゃがいも）、スキーリゾート、大自然",
      education_highlights: "Boise State University、University of Idaho等",
      international_students: "手頃な学費と安全な環境",
      job_opportunities: "テクノロジー、農業、アウトドア産業で成長中",
      description: "「ジェムステート」の愛称を持つ、宝石と自然の美しさに恵まれた州。全米のじゃがいも生産の約3分の1を占める農業州として有名だが、近年はボイシを中心にテクノロジー産業が急成長。カリフォルニアからの移住者が増え、「次のテックハブ」として注目を集めている。生活費が低く、治安も良好で、スキーやハイキングなどアウトドア活動が身近にある環境は、勉強とレジャーの両立に最適。"
    },
    "IL" => {
      name: "イリノイ州",
      english_name: "Illinois",
      nickname: "プレーリーステート",
      capital: "スプリングフィールド",
      largest_city: "シカゴ",
      population: "約1,270万人",
      area: "149,997 km²",
      climate: "湿潤大陸性気候",
      average_temp: "年間平均気温：8-12°C",
      cost_of_living: "中程度（全米平均の95-105%）",
      economy: "金融、製造業、農業、テクノロジー、物流",
      famous_for: "シカゴ、摩天楼建築、ディープディッシュピザ、ブルース音楽",
      education_highlights: "University of Chicago、Northwestern、UIUC等の世界的名門校",
      international_students: "国際都市シカゴでの多様な経験",
      job_opportunities: "金融、コンサルティング、テクノロジー、製造業で豊富",
      description: "アメリカ第3の都市シカゴを擁する中西部の中心地。シカゴはニューヨーク、ロサンゼルスに次ぐ経済規模を持ち、金融、コンサルティング、テクノロジー企業が集結する。University of Chicagoは経済学で世界最高峰、Northwesternはジャーナリズムとビジネスで名高く、UIUCは工学・コンピュータサイエンスで全米トップクラス。冬は厳しいが、世界クラスの美術館、音楽シーン、建築美を楽しめる文化的に豊かな環境。"
    },
    "IN" => {
      name: "インディアナ州",
      english_name: "Indiana",
      nickname: "フージャーステート",
      capital: "インディアナポリス",
      largest_city: "インディアナポリス",
      population: "約680万人",
      area: "94,326 km²",
      climate: "湿潤大陸性気候",
      average_temp: "年間平均気温：10-13°C",
      cost_of_living: "低い（全米平均の85-95%）",
      economy: "製造業、農業、物流、ヘルスケア、スポーツ",
      famous_for: "インディ500、バスケットボール、農業、製造業",
      education_highlights: "Purdue University、Notre Dame、Indiana University等",
      international_students: "手頃な学費と中西部の温かいコミュニティ",
      job_opportunities: "製造業、ヘルスケア、物流、テクノロジー分野",
      description: "アメリカ中西部の「クロスロード（交差点）」として知られ、主要高速道路が交差する物流の要所。世界最古にして最大の自動車レース「インディ500」の開催地として有名。Purdue Universityは航空宇宙工学で全米トップクラス、多くの宇宙飛行士を輩出している。Notre Dameはカレッジフットボールの名門として知られる。生活費が低く、治安も良好で、アメリカの「ハートランド」らしい親しみやすさが特徴。"
    },
    "IA" => {
      name: "アイオワ州",
      english_name: "Iowa",
      nickname: "ホークアイステート",
      capital: "デモイン",
      largest_city: "デモイン",
      population: "約320万人",
      area: "145,746 km²",
      climate: "湿潤大陸性気候",
      average_temp: "年間平均気温：8-11°C",
      cost_of_living: "低い（全米平均の85-90%）",
      economy: "農業、製造業、金融、保険、再生可能エネルギー",
      famous_for: "大統領選の最初の党員集会、トウモロコシ、豚肉生産",
      education_highlights: "University of Iowa、Iowa State University等",
      international_students: "非常に手頃な学費とフレンドリーな環境",
      job_opportunities: "農業テクノロジー、保険、製造業分野",
      description: "アメリカの「穀倉地帯」の中心に位置し、トウモロコシと大豆の生産で全米トップクラスを誇る農業州。4年に一度の大統領選挙では最初に党員集会が行われ、政治ニュースの中心となる。University of Iowaのライティング・プログラムは全米最高峰、Iowa State Universityは農学と工学で名高い。生活費が非常に低く、教育の質は高い。風力発電では全米でもトップクラスのシェアを持ち、再生可能エネルギー分野も成長中。"
    },
    "KS" => {
      name: "カンザス州",
      english_name: "Kansas",
      nickname: "サンフラワーステート",
      capital: "トピカ",
      largest_city: "ウィチタ",
      population: "約295万人",
      area: "213,100 km²",
      climate: "半乾燥気候～湿潤大陸性気候",
      average_temp: "年間平均気温：12-15°C",
      cost_of_living: "低い（全米平均の85-90%）",
      economy: "航空機製造、農業、エネルギー、製造業",
      famous_for: "「オズの魔法使い」、小麦生産、航空機産業",
      education_highlights: "University of Kansas、Kansas State University等",
      international_students: "手頃な学費と安全な環境",
      job_opportunities: "航空機製造、農業、エネルギー分野",
      description: "アメリカのほぼ中央に位置し、広大な平原とひまわり畑が広がる「サンフラワーステート」。「オズの魔法使い」のドロシーの故郷としても有名。ウィチタは「世界の航空機の首都」と呼ばれ、セスナ、ビーチクラフト、ボーイングなどの航空機メーカーが集結。小麦生産量は全米トップで、農業技術の研究も盛ん。生活費が低く、治安の良い環境で、アメリカの「ハートランド」を体験できる。"
    },
    "KY" => {
      name: "ケンタッキー州",
      english_name: "Kentucky",
      nickname: "ブルーグラスステート",
      capital: "フランクフォート",
      largest_city: "ルイビル",
      population: "約450万人",
      area: "104,656 km²",
      climate: "湿潤亜熱帯気候",
      average_temp: "年間平均気温：12-15°C",
      cost_of_living: "低い（全米平均の85-95%）",
      economy: "自動車製造、物流、ヘルスケア、農業、蒸留酒産業",
      famous_for: "ケンタッキーダービー、バーボンウイスキー、ブルーグラス音楽",
      education_highlights: "University of Kentucky、University of Louisville等",
      international_students: "手頃な学費と南部のホスピタリティ",
      job_opportunities: "自動車製造、物流、ヘルスケア分野",
      description: "美しいブルーグラス（牧草）の丘陵地帯と競馬文化で知られる州。世界的に有名なケンタッキーダービーは毎年5月に開催され、アメリカ文化の象徴的イベント。世界のバーボンウイスキーの95%がここで生産されており、蒸留所ツアーは人気の観光アクティビティ。トヨタ、フォードなど自動車メーカーの工場が多く、製造業が盛ん。南部と中西部の文化が交わる独特の雰囲気と、手頃な生活費が魅力。"
    },
    "LA" => {
      name: "ルイジアナ州",
      english_name: "Louisiana",
      nickname: "ペリカンステート",
      capital: "バトンルージュ",
      largest_city: "ニューオーリンズ",
      population: "約465万人",
      area: "135,659 km²",
      climate: "亜熱帯湿潤気候",
      average_temp: "年間平均気温：18-22°C",
      cost_of_living: "低い（全米平均の90-95%）",
      economy: "エネルギー、石油化学、港湾物流、観光、農業",
      famous_for: "ニューオーリンズ、ジャズ音楽、マルディグラ、ケイジャン料理",
      education_highlights: "Tulane University、LSU等",
      international_students: "ユニークな文化体験とフレンドリーな環境",
      job_opportunities: "エネルギー、石油化学、港湾物流分野",
      description: "フランス植民地時代の影響が色濃く残る、アメリカで最もユニークな文化を持つ州の一つ。ニューオーリンズはジャズ発祥の地として知られ、毎年のマルディグラ（謝肉祭）には世界中から観光客が訪れる。ケイジャン・クレオール料理は独自の食文化を形成。メキシコ湾岸の石油・天然ガス産業が経済の柱で、エネルギー工学を学ぶ学生に実践的な機会を提供。温暖な気候と陽気な人々、そして他では味わえない文化体験が待っている。"
    },
    "ME" => {
      name: "メイン州",
      english_name: "Maine",
      nickname: "パインツリーステート",
      capital: "オーガスタ",
      largest_city: "ポートランド",
      population: "約135万人",
      area: "91,633 km²",
      climate: "湿潤大陸性気候",
      average_temp: "年間平均気温：4-8°C",
      cost_of_living: "中程度（全米平均の95-105%）",
      economy: "観光、漁業、林業、製造業、ヘルスケア",
      famous_for: "ロブスター、アケイディア国立公園、美しい海岸線",
      education_highlights: "Bowdoin College、Bates College、Colby College等",
      international_students: "小規模リベラルアーツカレッジでの濃密な学び",
      job_opportunities: "観光、ヘルスケア、海洋関連産業",
      description: "アメリカ本土最北東に位置し、美しい岩場の海岸線と広大な森林が広がるニューイングランドの州。ロブスターの産地として世界的に有名で、新鮮なシーフードが日常的に楽しめる。Bowdoin、Bates、Colbyの「メインリベラルアーツトライアングル」は、少人数制の質の高い教育で知られる。冬は厳しいが、夏の短い期間は避暑地として賑わう。自然の中での静かな学習環境を求める学生に最適。"
    },
    "MD" => {
      name: "メリーランド州",
      english_name: "Maryland",
      nickname: "オールドラインステート",
      capital: "アナポリス",
      largest_city: "ボルチモア",
      population: "約615万人",
      area: "32,131 km²",
      climate: "湿潤亜熱帯気候",
      average_temp: "年間平均気温：11-15°C",
      cost_of_living: "高い（全米平均の110-125%）",
      economy: "バイオテクノロジー、サイバーセキュリティ、政府、ヘルスケア",
      famous_for: "チェサピーク湾のカニ、ジョンズ・ホプキンス大学、国立衛生研究所",
      education_highlights: "Johns Hopkins、University of Maryland等の研究重視校",
      international_students: "ワシントンDCへの近接性と研究機会",
      job_opportunities: "バイオテクノロジー、サイバーセキュリティ、政府関連で豊富",
      description: "ワシントンDCを囲む戦略的立地で、連邦政府機関や研究施設が多数集まる州。ジョンズ・ホプキンス大学は医学・公衆衛生で世界最高峰、その付属病院は全米ランキング常連。国立衛生研究所（NIH）やNSA本部があり、生命科学やサイバーセキュリティ分野でのインターンシップ・就職機会が豊富。チェサピーク湾の美しい水辺とブルークラブ（青いカニ）料理も魅力。DCの政治・文化へのアクセスと郊外の落ち着きを両立できる。"
    },
    "MA" => {
      name: "マサチューセッツ州",
      english_name: "Massachusetts",
      nickname: "ベイステート",
      capital: "ボストン",
      largest_city: "ボストン",
      population: "約700万人",
      area: "27,336 km²",
      climate: "湿潤大陸性気候",
      average_temp: "年間平均気温：8-12°C",
      cost_of_living: "高い（全米平均の125-145%）",
      economy: "バイオテクノロジー、テクノロジー、金融、教育、ヘルスケア",
      famous_for: "ハーバード、MIT、アメリカ独立の歴史、美しい秋の紅葉",
      education_highlights: "Harvard、MIT、Tufts、Boston University等の世界最高レベルの大学群",
      international_students: "最高水準の教育研究環境、活発な学生コミュニティ",
      job_opportunities: "バイオテック、AI、フィンテック、ヘルスケアで世界最高レベル",
      description: "アメリカ教育の聖地、ボストンを中心に世界最高峰の大学が集中する州。ハーバードとMITは言わずと知れた世界トップ校で、両校を中心としたケンブリッジ地区は「世界で最も知的な平方マイル」と呼ばれる。バイオテクノロジー産業ではサンフランシスコと並ぶ世界の二大拠点の一つで、モデルナなど多くの製薬企業が研究所を構える。アメリカ独立の歴史を感じる街並みと、美しいニューイングランドの秋の紅葉も魅力。"
    },
    "MI" => {
      name: "ミシガン州",
      english_name: "Michigan",
      nickname: "グレートレイクステート",
      capital: "ランシング",
      largest_city: "デトロイト",
      population: "約1,000万人",
      area: "250,493 km²",
      climate: "湿潤大陸性気候",
      average_temp: "年間平均気温：6-10°C",
      cost_of_living: "低い（全米平均の90-100%）",
      economy: "自動車産業、製造業、農業、テクノロジー、ヘルスケア",
      famous_for: "自動車産業の中心地、五大湖、モータウン音楽",
      education_highlights: "University of Michigan、Michigan State等の優秀な州立大学",
      international_students: "手頃な学費と充実した研究環境",
      job_opportunities: "自動車、EV、製造業、テクノロジー分野で復活中",
      description: "五大湖のうち4つに囲まれた「グレートレイクステート」は、アメリカ自動車産業の発祥地。デトロイトはフォード、GM、クライスラー（現ステランティス）の本拠地として一世を風靡し、現在はEV（電気自動車）産業の中心地として再び注目を集めている。University of Michiganは全米トップ10の州立大学で、工学、医学、ビジネスなど幅広い分野で高い評価を得ている。生活費は低めで、湖畔のアウトドア活動も楽しめる環境。"
    },
    "MN" => {
      name: "ミネソタ州",
      english_name: "Minnesota",
      nickname: "ノーススターステート",
      capital: "セントポール",
      largest_city: "ミネアポリス",
      population: "約570万人",
      area: "225,163 km²",
      climate: "湿潤大陸性気候",
      average_temp: "年間平均気温：4-9°C",
      cost_of_living: "中程度（全米平均の95-105%）",
      economy: "ヘルスケア、金融、製造業、農業、小売",
      famous_for: "10,000の湖、ミネアポリス美術館、モール・オブ・アメリカ",
      education_highlights: "University of Minnesota、Carleton College等",
      international_students: "質の高い生活環境と充実した公共サービス",
      job_opportunities: "ヘルスケア、金融、テクノロジー、小売分野",
      description: "「10,000の湖の州」として知られる美しい自然環境と、全米トップクラスの生活の質を誇る州。ミネアポリス・セントポール双子都市には、ターゲット、ベストバイ、UnitedHealthなどフォーチュン500企業が17社も本社を置く。Mayo Clinicは世界最高の医療機関として知られ、医学を志す学生の憧れ。冬は非常に厳しいが、その分人々は温かく、「ミネソタ・ナイス」と呼ばれるフレンドリーさが特徴。教育水準と住民の幸福度は常に全米上位。"
    },
    "MS" => {
      name: "ミシシッピ州",
      english_name: "Mississippi",
      nickname: "マグノリアステート",
      capital: "ジャクソン",
      largest_city: "ジャクソン",
      population: "約295万人",
      area: "125,438 km²",
      climate: "亜熱帯湿潤気候",
      average_temp: "年間平均気温：17-20°C",
      cost_of_living: "非常に低い（全米平均の80-85%）",
      economy: "農業、製造業、軍事、ヘルスケア",
      famous_for: "ブルース音楽の発祥地、ミシシッピ川、南部文化",
      education_highlights: "University of Mississippi（Ole Miss）、Mississippi State等",
      international_students: "全米最低水準の生活費、温かい南部のホスピタリティ",
      job_opportunities: "製造業、ヘルスケア、農業分野",
      description: "ブルース音楽の故郷として知られ、エルヴィス・プレスリーやB.B.キングなど伝説的ミュージシャンを輩出した州。生活費は全米で最も低い水準にあり、留学費用を最小限に抑えたい学生に最適。温暖な気候と南部特有のスローなライフスタイル、「Y'all come back」のホスピタリティが心地よい環境を作る。University of Mississippiの法学部は南部で高い評価を受け、文学・南部研究でも知られる。"
    },
    "MO" => {
      name: "ミズーリ州",
      english_name: "Missouri",
      nickname: "ショーミーステート",
      capital: "ジェファーソンシティ",
      largest_city: "カンザスシティ",
      population: "約615万人",
      area: "180,540 km²",
      climate: "湿潤大陸性気候",
      average_temp: "年間平均気温：11-15°C",
      cost_of_living: "低い（全米平均の85-95%）",
      economy: "航空宇宙、自動車製造、農業、金融、ヘルスケア",
      famous_for: "ゲートウェイアーチ、BBQ、ジャズとブルース",
      education_highlights: "Washington University in St. Louis、University of Missouri等",
      international_students: "手頃な学費と中西部の温かい環境",
      job_opportunities: "航空宇宙、ヘルスケア、金融、テクノロジー分野",
      description: "「西部への玄関口」として知られ、セントルイスのゲートウェイアーチが象徴的なランドマーク。Washington University in St. Louisは全米トップ20の私立大学で、医学部と法学部は特に名高い。カンザスシティはBBQの聖地として有名で、ジャズの歴史も深い。アメリカの中央に位置し、東西海岸のどちらへもアクセスしやすい。生活費が低く、大都市の便利さと中西部の親しみやすさを兼ね備えた環境。"
    },
    "MT" => {
      name: "モンタナ州",
      english_name: "Montana",
      nickname: "トレジャーステート",
      capital: "ヘレナ",
      largest_city: "ビリングス",
      population: "約110万人",
      area: "380,831 km²",
      climate: "半乾燥気候～高山気候",
      average_temp: "年間平均気温：4-9°C",
      cost_of_living: "中程度（全米平均の95-100%）",
      economy: "農業、鉱業、観光、林業",
      famous_for: "グレーシャー国立公園、イエローストーン（一部）、ビッグスカイ",
      education_highlights: "University of Montana、Montana State University等",
      international_students: "大自然の中での学習と研究機会",
      job_opportunities: "環境科学、農業、観光分野",
      description: "「ビッグスカイ・カントリー」の愛称通り、見渡す限りの大空と雄大なロッキー山脈が広がる州。グレーシャー国立公園は氷河と野生動物の宝庫で、環境科学や野生動物学を学ぶ学生のフィールドワーク先として人気。人口密度は全米で3番目に低く、静かで集中できる学習環境が魅力。消費税がなく、アウトドア活動（スキー、ハイキング、釣り等）が身近にある生活は、都会とは違った豊かさを提供する。"
    },
    "NE" => {
      name: "ネブラスカ州",
      english_name: "Nebraska",
      nickname: "コーンハスカーステート",
      capital: "リンカーン",
      largest_city: "オマハ",
      population: "約195万人",
      area: "200,330 km²",
      climate: "湿潤大陸性気候～半乾燥気候",
      average_temp: "年間平均気温：9-12°C",
      cost_of_living: "低い（全米平均の85-95%）",
      economy: "農業、食品加工、保険、テクノロジー",
      famous_for: "トウモロコシ、牛肉、ウォーレン・バフェット、カレッジフットボール",
      education_highlights: "University of Nebraska、Creighton University等",
      international_students: "手頃な学費と安全なコミュニティ",
      job_opportunities: "農業テクノロジー、保険、金融分野",
      description: "「投資の神様」ウォーレン・バフェットの故郷であり、バークシャー・ハサウェイ本社があるオマハを擁する州。農業が盛んで、牛肉生産量は全米トップクラス。University of Nebraskaのカレッジフットボールチーム「コーンハスカーズ」は全米で最も熱狂的なファンベースを持つ。生活費が低く、治安も良好で、中西部らしい温かいコミュニティが特徴。農業テクノロジーやデータサイエンス分野での研究も進んでいる。"
    },
    "NV" => {
      name: "ネバダ州",
      english_name: "Nevada",
      nickname: "シルバーステート",
      capital: "カーソンシティ",
      largest_city: "ラスベガス",
      population: "約320万人",
      area: "286,380 km²",
      climate: "砂漠気候～半乾燥気候",
      average_temp: "年間平均気温：10-20°C",
      cost_of_living: "中程度（全米平均の100-110%）",
      economy: "観光・カジノ、鉱業、テクノロジー、物流",
      famous_for: "ラスベガス、カジノ、エンターテインメント、砂漠",
      education_highlights: "University of Nevada Las Vegas、University of Nevada Reno等",
      international_students: "ユニークな環境とホスピタリティ産業での経験",
      job_opportunities: "観光、エンターテインメント、テクノロジー、再生可能エネルギー分野",
      description: "「世界のエンターテインメントの首都」ラスベガスを擁する砂漠の州。カジノとショービジネスで有名だが、近年はテスラのギガファクトリーやGoogleのデータセンターなどテクノロジー産業の進出が相次ぐ。州所得税がなく、カリフォルニアからの企業・人口流入が続いている。ホスピタリティ・マネジメントを学ぶには最高の実践環境で、UNLVのホテル経営学部は世界トップクラス。砂漠の気候は乾燥しているが、過ごしやすい。"
    },
    "NH" => {
      name: "ニューハンプシャー州",
      english_name: "New Hampshire",
      nickname: "グラニットステート",
      capital: "コンコード",
      largest_city: "マンチェスター",
      population: "約140万人",
      area: "24,214 km²",
      climate: "湿潤大陸性気候",
      average_temp: "年間平均気温：6-10°C",
      cost_of_living: "中程度（全米平均の100-110%）",
      economy: "製造業、テクノロジー、観光、教育",
      famous_for: "大統領選の最初のプライマリー、美しい秋の紅葉、スキー",
      education_highlights: "Dartmouth College、University of New Hampshire等",
      international_students: "小規模で親密な学習環境",
      job_opportunities: "テクノロジー、製造業、ヘルスケア分野",
      description: "ニューイングランドの美しい自然と歴史的な町並みが魅力の州。アイビーリーグの一つダートマス大学があり、少人数制の質の高いリベラルアーツ教育で知られる。大統領選挙では最初のプライマリー（予備選）が行われ、政治的に重要な州。消費税と州所得税がない珍しい州で、買い物はお得。秋の紅葉は全米で最も美しいとされ、冬はスキーリゾートで賑わう。ボストンへのアクセスも良好。"
    },
    "NJ" => {
      name: "ニュージャージー州",
      english_name: "New Jersey",
      nickname: "ガーデンステート",
      capital: "トレントン",
      largest_city: "ニューアーク",
      population: "約920万人",
      area: "22,591 km²",
      climate: "湿潤大陸性気候",
      average_temp: "年間平均気温：10-14°C",
      cost_of_living: "高い（全米平均の115-130%）",
      economy: "製薬、金融、テクノロジー、物流、製造業",
      famous_for: "プリンストン大学、製薬産業、ジャージーショア、ニューヨーク近郊",
      education_highlights: "Princeton University、Rutgers University、Stevens Institute等",
      international_students: "世界トップ大学とニューヨークへのアクセス",
      job_opportunities: "製薬、金融、テクノロジー、物流分野で豊富",
      description: "ニューヨークとフィラデルフィアに挟まれた戦略的立地で、両大都市への通勤圏内という利便性が最大の魅力。アイビーリーグのプリンストン大学は学部教育の質で全米トップの評価を受ける。ジョンソン・エンド・ジョンソン、メルク、ブリストル・マイヤーズスクイブなど大手製薬企業の本社が集中し、「アメリカの薬箱」と呼ばれる。「ガーデンステート」の愛称通り、郊外は緑豊かな住宅地が広がる。"
    },
    "NM" => {
      name: "ニューメキシコ州",
      english_name: "New Mexico",
      nickname: "エンチャントメントの地",
      capital: "サンタフェ",
      largest_city: "アルバカーキ",
      population: "約210万人",
      area: "314,917 km²",
      climate: "砂漠気候～半乾燥気候",
      average_temp: "年間平均気温：10-16°C",
      cost_of_living: "低い（全米平均の90-95%）",
      economy: "国立研究所、航空宇宙、観光、エネルギー、映画産業",
      famous_for: "サンタフェのアート、国立研究所、先住民文化、赤い岩の風景",
      education_highlights: "University of New Mexico、New Mexico Tech等",
      international_students: "ユニークな文化体験と研究機会",
      job_opportunities: "国立研究所、航空宇宙、再生可能エネルギー分野",
      description: "スペイン植民地時代と先住民の文化が融合した「エンチャントメント（魅惑）の地」。サンタフェはアメリカ最古の州都で、アートギャラリーとアドビ建築が美しい芸術の街。ロスアラモス国立研究所とサンディア国立研究所があり、物理学や核科学の研究では世界最先端。砂漠と山岳の壮大な風景、独自のスパイシーな料理文化、そしてアメリカとは思えないエキゾチックな雰囲気が魅力。"
    },
    "NY" => {
      name: "ニューヨーク州",
      english_name: "New York",
      nickname: "エンパイアステート",
      capital: "オルバニー",
      largest_city: "ニューヨーク市",
      population: "約1,950万人",
      area: "141,300 km²",
      climate: "湿潤大陸性気候",
      average_temp: "年間平均気温：8-13°C",
      cost_of_living: "高い（全米平均の130-180%）",
      economy: "金融、メディア、テクノロジー、ファッション、芸術、観光",
      famous_for: "ウォール街、ブロードウェイ、自由の女神、タイムズスクエア",
      education_highlights: "Columbia、NYU、Cornell、ロチェスター等の世界的名門校",
      international_students: "世界で最も多様な国際都市での無限の経験",
      job_opportunities: "金融、メディア、テクノロジー、ファッション、芸術で世界最高レベル",
      description: "世界の金融・メディア・芸術の中心地ニューヨーク市を擁する「エンパイアステート」。ウォール街は世界金融の心臓部、ブロードウェイはミュージカルの聖地、国連本部は国際政治の舞台。コロンビア大学、NYU、コーネル大学など世界トップクラスの大学が集まり、留学生数も全米屈指。生活費は高いが、インターンシップやネットワーキングの機会は他の追随を許さない。アップステート（北部）にはナイアガラの滝や美しい自然も広がる。"
    },
    "NC" => {
      name: "ノースカロライナ州",
      english_name: "North Carolina",
      nickname: "タールヒールステート",
      capital: "ローリー",
      largest_city: "シャーロット",
      population: "約1,070万人",
      area: "139,391 km²",
      climate: "亜熱帯湿潤気候",
      average_temp: "年間平均気温：14-18°C",
      cost_of_living: "低め（全米平均の90-100%）",
      economy: "テクノロジー、金融、バイオテクノロジー、製造業、農業",
      famous_for: "リサーチトライアングル、バンクオブアメリカ本社、ライト兄弟初飛行の地",
      education_highlights: "Duke University、UNC Chapel Hill、NC State等の名門校",
      international_students: "成長するテック産業と手頃な生活費",
      job_opportunities: "テクノロジー、金融、バイオテクノロジー、ヘルスケア分野で急成長",
      description: "アメリカ東海岸で最も急成長している州の一つ。ローリー、ダーラム、チャペルヒルを結ぶ「リサーチトライアングル」は、Duke、UNC、NC Stateの3大学を核としたテクノロジー・バイオテクノロジーのハブ。シャーロットはニューヨークに次ぐ全米第2の金融センターで、バンクオブアメリカの本社がある。山から海まで多様な自然環境、温暖な気候、手頃な生活費、そして成長する経済が、多くの移住者を引きつけている。"
    },
    "ND" => {
      name: "ノースダコタ州",
      english_name: "North Dakota",
      nickname: "ピースガーデンステート",
      capital: "ビスマーク",
      largest_city: "ファーゴ",
      population: "約78万人",
      area: "183,108 km²",
      climate: "湿潤大陸性気候",
      average_temp: "年間平均気温：3-7°C",
      cost_of_living: "低い（全米平均の85-95%）",
      economy: "農業、エネルギー（石油・風力）、製造業",
      famous_for: "広大な平原、セオドア・ルーズベルト国立公園、シェール石油",
      education_highlights: "University of North Dakota等",
      international_students: "小規模コミュニティでの密な教育",
      job_opportunities: "エネルギー、農業、ヘルスケア分野",
      description: "広大な平原と空の大きさが印象的な、アメリカ中北部の農業州。近年はバッケン層のシェールオイル開発で経済ブームを経験し、エネルギー産業が成長。失業率は常に全米最低水準で、安定した経済が特徴。冬は非常に厳しいが、その分コミュニティの絆は強く、留学生への温かいサポートが期待できる。生活費が低く、静かな環境で勉強に集中したい学生に向いている。"
    },
    "OH" => {
      name: "オハイオ州",
      english_name: "Ohio",
      nickname: "バックアイステート",
      capital: "コロンバス",
      largest_city: "コロンバス",
      population: "約1,170万人",
      area: "116,096 km²",
      climate: "湿潤大陸性気候",
      average_temp: "年間平均気温：9-13°C",
      cost_of_living: "低い（全米平均の85-95%）",
      economy: "製造業、ヘルスケア、金融、テクノロジー、農業",
      famous_for: "ライト兄弟（航空の父）、ロックの殿堂、オハイオステート大学フットボール",
      education_highlights: "Ohio State University、Case Western Reserve、Oberlin等",
      international_students: "手頃な学費と多様な教育機会",
      job_opportunities: "製造業、ヘルスケア、テクノロジー分野で豊富",
      description: "「航空の父」ライト兄弟や多くの宇宙飛行士を輩出した「夢を実現する州」。オハイオステート大学は学生数全米最大級のマンモス校で、工学、ビジネス、医学で高い評価を得ている。Case Western Reserveは医学・工学の研究大学として名高い。クリーブランドにはロックンロールの殿堂があり、音楽文化も豊か。生活費が低く、製造業からテクノロジーまで幅広い産業があり、インターンシップや就職の機会も豊富。"
    },
    "OK" => {
      name: "オクラホマ州",
      english_name: "Oklahoma",
      nickname: "スーナーステート",
      capital: "オクラホマシティ",
      largest_city: "オクラホマシティ",
      population: "約400万人",
      area: "181,037 km²",
      climate: "湿潤亜熱帯気候～半乾燥気候",
      average_temp: "年間平均気温：14-17°C",
      cost_of_living: "低い（全米平均の85-90%）",
      economy: "エネルギー、航空宇宙、農業、バイオテクノロジー",
      famous_for: "先住民文化、オイル産業、竜巻（トルネードアレー）、ルート66",
      education_highlights: "University of Oklahoma、Oklahoma State University等",
      international_students: "非常に手頃な学費と温かいコミュニティ",
      job_opportunities: "エネルギー、航空宇宙、ヘルスケア分野",
      description: "アメリカ先住民の人口比率が最も高い州の一つで、39の部族が主権を持つ「インディアン・カントリー」。石油・天然ガス産業の中心地として発展し、現在も経済の柱となっている。「トルネードアレー」の中心に位置し、竜巻研究では世界をリード。University of Oklahomaの気象学プログラムは全米トップクラス。生活費と学費が非常に低く、フレンドリーな南部文化が特徴。"
    },
    "OR" => {
      name: "オレゴン州",
      english_name: "Oregon",
      nickname: "ビーバーステート",
      capital: "セーラム",
      largest_city: "ポートランド",
      population: "約420万人",
      area: "254,799 km²",
      climate: "海洋性気候～半乾燥気候",
      average_temp: "年間平均気温：9-13°C",
      cost_of_living: "中程度（全米平均の100-115%）",
      economy: "テクノロジー、林業、農業、観光、製造業",
      famous_for: "ポートランドの独自文化、クレーターレイク、ワイン産地、自然環境保護",
      education_highlights: "University of Oregon、Oregon State、Reed College等",
      international_students: "環境意識の高いコミュニティとアウトドア文化",
      job_opportunities: "テクノロジー、環境関連、クリエイティブ産業",
      description: "「Keep Portland Weird（ポートランドを変わり者のままに）」のスローガンで知られる、独自のカウンターカルチャーが根付く州。ナイキ、インテルのプロセッサ工場があり、「シリコンフォレスト」と呼ばれるテックハブも形成。消費税がなく、買い物が安い。環境保護意識が高く、オーガニック食品やサステナビリティへの関心が強い。クレーターレイク国立公園や太平洋岸の美しい海岸線など、自然も豊か。"
    },
    "PA" => {
      name: "ペンシルベニア州",
      english_name: "Pennsylvania",
      nickname: "キーストーンステート",
      capital: "ハリスバーグ",
      largest_city: "フィラデルフィア",
      population: "約1,290万人",
      area: "119,280 km²",
      climate: "湿潤大陸性気候",
      average_temp: "年間平均気温：9-13°C",
      cost_of_living: "中程度（全米平均の95-105%）",
      economy: "ヘルスケア、製造業、金融、エネルギー、テクノロジー",
      famous_for: "独立宣言の地、自由の鐘、チーズステーキ、アーミッシュ",
      education_highlights: "UPenn、Carnegie Mellon、Swarthmore、Penn State等の名門校",
      international_students: "歴史ある学術環境と多様な産業機会",
      job_opportunities: "ヘルスケア、テクノロジー、金融、製造業分野",
      description: "1776年に独立宣言が署名されたフィラデルフィアを擁する、アメリカ建国の歴史が詰まった州。アイビーリーグのペンシルベニア大学（UPenn）はビジネススクールのウォートンで世界最高峰、カーネギーメロン大学はコンピュータサイエンスとAI研究で名高い。ピッツバーグは「鉄鋼の街」から「医療・テクノロジーの街」へと見事に変貌を遂げた。アーミッシュの素朴な暮らしが見られるランカスター郡など、多様な文化体験も魅力。"
    },
    "RI" => {
      name: "ロードアイランド州",
      english_name: "Rhode Island",
      nickname: "オーシャンステート",
      capital: "プロビデンス",
      largest_city: "プロビデンス",
      population: "約110万人",
      area: "4,001 km²",
      climate: "湿潤大陸性気候",
      average_temp: "年間平均気温：9-12°C",
      cost_of_living: "中程度（全米平均の100-110%）",
      economy: "ヘルスケア、教育、製造業、観光",
      famous_for: "アメリカ最小の州、豪華なニューポート邸宅、美しい海岸線",
      education_highlights: "Brown University、Rhode Island School of Design（RISD）等",
      international_students: "小規模ながら質の高い教育環境",
      job_opportunities: "ヘルスケア、教育、デザイン分野",
      description: "アメリカ最小の州ながら、アイビーリーグのブラウン大学と世界最高のアート・デザイン学校RISD（リズディー）を擁する教育のパワーハウス。ブラウンは「オープンカリキュラム」で学生の自由な学びを尊重し、RISDはデザイン界のハーバードと呼ばれる。ニューポートには金ぴか時代の大富豪の豪邸が並び、アメリカの歴史を感じられる。海に面した美しいロケーションと、ボストンへのアクセスの良さも魅力。"
    },
    "SC" => {
      name: "サウスカロライナ州",
      english_name: "South Carolina",
      nickname: "パルメットステート",
      capital: "コロンビア",
      largest_city: "チャールストン",
      population: "約520万人",
      area: "82,933 km²",
      climate: "亜熱帯湿潤気候",
      average_temp: "年間平均気温：16-20°C",
      cost_of_living: "低い（全米平均の90-95%）",
      economy: "製造業（自動車・航空機）、観光、農業、軍事",
      famous_for: "チャールストンの歴史的街並み、美しいビーチ、南部のホスピタリティ",
      education_highlights: "Clemson University、University of South Carolina等",
      international_students: "手頃な学費と温暖な気候",
      job_opportunities: "自動車製造、航空宇宙、観光分野",
      description: "南部の魅力が凝縮された州。チャールストンは何度も「アメリカで最も魅力的な都市」に選ばれ、歴史的なプランテーション、石畳の通り、そして絶品の南部料理で観光客を魅了する。BMW、ボーイング、ボルボなど自動車・航空機メーカーの工場があり、製造業が成長中。温暖な気候、手頃な生活費、そして「サザンホスピタリティ」と呼ばれる温かいおもてなしの文化が、留学生を歓迎する環境を作っている。"
    },
    "SD" => {
      name: "サウスダコタ州",
      english_name: "South Dakota",
      nickname: "マウントラシュモアステート",
      capital: "ピア",
      largest_city: "スーフォールズ",
      population: "約90万人",
      area: "199,729 km²",
      climate: "湿潤大陸性気候～半乾燥気候",
      average_temp: "年間平均気温：6-10°C",
      cost_of_living: "低い（全米平均の90-95%）",
      economy: "農業、観光、金融サービス、製造業",
      famous_for: "マウントラシュモア、バッドランズ国立公園、クレイジーホース記念碑",
      education_highlights: "South Dakota State University等",
      international_students: "小規模で安全なコミュニティ",
      job_opportunities: "農業、観光、ヘルスケア分野",
      description: "4人の大統領の顔が彫られたマウントラシュモアで世界的に有名な州。バッドランズ国立公園の壮大な地形や、現在も建設中のクレイジーホース記念碑など、壮大なスケールの観光名所が点在。州所得税がなく、ビジネスに有利な環境からクレジットカード会社の多くが本社を置く。生活費が低く、治安も良好で、広大な草原と空の下でのんびりとした留学生活を送りたい学生に向いている。"
    },
    "TN" => {
      name: "テネシー州",
      english_name: "Tennessee",
      nickname: "ボランティアステート",
      capital: "ナッシュビル",
      largest_city: "ナッシュビル",
      population: "約700万人",
      area: "109,153 km²",
      climate: "亜熱帯湿潤気候",
      average_temp: "年間平均気温：14-17°C",
      cost_of_living: "低い（全米平均の90-95%）",
      economy: "ヘルスケア、自動車製造、音楽産業、観光",
      famous_for: "ナッシュビル（カントリー音楽）、メンフィス（ブルース・ロック）、グレートスモーキー山脈",
      education_highlights: "Vanderbilt University、University of Tennessee等",
      international_students: "手頃な学費と活気ある音楽シーン",
      job_opportunities: "ヘルスケア、自動車、音楽・エンターテインメント分野",
      description: "アメリカ音楽の聖地。ナッシュビルは「ミュージックシティ」としてカントリー音楽の中心地、メンフィスはエルヴィス・プレスリーのグレースランドがありロックンロールとブルースの発祥地。近年ナッシュビルは全米で最も成長している都市の一つで、アマゾンの大規模オフィス進出など企業誘致にも成功。Vanderbilt Universityは南部最高峰の名門私立大学。州所得税がなく、手頃な生活費と温暖な気候、そして音楽があふれる環境が魅力。"
    },
    "TX" => {
      name: "テキサス州",
      english_name: "Texas",
      nickname: "ローンスターステート",
      capital: "オースティン",
      largest_city: "ヒューストン",
      population: "約3,000万人",
      area: "695,662 km²",
      climate: "亜熱帯～砂漠気候",
      average_temp: "年間平均気温：18-25°C",
      cost_of_living: "中程度（全米平均の90-105%）",
      economy: "エネルギー、テクノロジー、航空宇宙、製造業、農業、ヘルスケア",
      famous_for: "NASA、石油産業、BBQ、カウボーイ文化、テックブーム",
      education_highlights: "UT Austin、Rice、Texas A&M、SMU等の優秀校",
      international_students: "急成長する経済と多様な文化環境",
      job_opportunities: "テクノロジー、エネルギー、航空宇宙、ヘルスケアで無限の機会",
      description: "「すべてが大きい」がモットーの、アメリカ本土最大の州。カリフォルニアに次ぐ経済規模を持ち、州所得税がないことからテクノロジー企業のカリフォルニアからの移転が相次ぐ。オースティンは「南のシリコンバレー」と呼ばれテスラ、オラクルが本社を移転、ヒューストンはNASAのジョンソン宇宙センターがあり宇宙産業の中心地。Rice Universityは科学技術で名高く、UT Austinは州立大学トップクラス。BBQ、テックス・メックス料理、カウボーイ文化など独自の魅力も満載。"
    },
    "UT" => {
      name: "ユタ州",
      english_name: "Utah",
      nickname: "ビーハイブステート",
      capital: "ソルトレイクシティ",
      largest_city: "ソルトレイクシティ",
      population: "約330万人",
      area: "219,882 km²",
      climate: "半乾燥気候～砂漠気候",
      average_temp: "年間平均気温：8-14°C",
      cost_of_living: "中程度（全米平均の95-105%）",
      economy: "テクノロジー、観光、鉱業、金融、ヘルスケア",
      famous_for: "5つの国立公園、スキーリゾート、モルモン教総本山",
      education_highlights: "University of Utah、Brigham Young University等",
      international_students: "テクノロジー産業の成長と美しい自然環境",
      job_opportunities: "テクノロジー、アウトドア産業、金融分野で急成長",
      description: "赤い岩の絶景と雪山のスキーリゾートという対照的な自然が魅力の州。「シリコンスロープ」と呼ばれるソルトレイクシティ周辺のテクノロジー産業が急成長し、Adobe、Qualtrics、Pluralsightなどの企業が拠点を構える。アーチーズ、ザイオン、ブライスキャニオンなど5つの国立公園があり、アウトドア愛好者の聖地。モルモン教の総本山として知られ、家族的で安全なコミュニティが特徴。若い人口構成と起業家精神あふれる環境。"
    },
    "VT" => {
      name: "バーモント州",
      english_name: "Vermont",
      nickname: "グリーンマウンテンステート",
      capital: "モントピリア",
      largest_city: "バーリントン",
      population: "約65万人",
      area: "24,906 km²",
      climate: "湿潤大陸性気候",
      average_temp: "年間平均気温：4-8°C",
      cost_of_living: "中程度（全米平均の100-110%）",
      economy: "観光、農業（酪農・メープルシロップ）、製造業、教育",
      famous_for: "メープルシロップ、紅葉、スキー、Ben & Jerry'sアイスクリーム",
      education_highlights: "University of Vermont、Middlebury College等",
      international_students: "小規模で環境意識の高いコミュニティ",
      job_opportunities: "観光、農業、環境関連分野",
      description: "全米で2番目に人口が少ない小さな州だが、その美しさと独自の価値観で知られる。メープルシロップ生産量は全米1位、Ben & Jerry'sアイスクリームの発祥地でもある。秋の紅葉は圧巻で、「フォリッジ・シーズン」には全米から観光客が訪れる。環境保護意識が非常に高く、オーガニック農業や地産地消の文化が根付く。Middlebury Collegeは語学教育で全米最高峰として知られる。都会の喧騒から離れた、自然と共に学ぶ環境。"
    },
    "VA" => {
      name: "バージニア州",
      english_name: "Virginia",
      nickname: "オールドドミニオン",
      capital: "リッチモンド",
      largest_city: "バージニアビーチ",
      population: "約860万人",
      area: "110,787 km²",
      climate: "亜熱帯湿潤気候",
      average_temp: "年間平均気温：12-16°C",
      cost_of_living: "中程度（全米平均の100-115%）",
      economy: "テクノロジー、政府、軍事、農業、観光",
      famous_for: "アメリカ建国の歴史、ワシントンDC近郊、バージニアワイン",
      education_highlights: "University of Virginia、Virginia Tech、William & Mary等",
      international_students: "政府機関との連携と豊富なインターンシップ機会",
      job_opportunities: "テクノロジー、政府、国防、サイバーセキュリティ分野で豊富",
      description: "8人の大統領を輩出した「大統領の母」とも呼ばれる、アメリカ建国の中心地。ワシントンDCに隣接する北バージニアはAmazon第2本社（HQ2）の建設地に選ばれ、テクノロジー産業が急成長中。国防総省（ペンタゴン）やCIAもバージニアに位置し、政府関連の就職機会が豊富。University of Virginiaはトーマス・ジェファーソンが設計した美しいキャンパスを持つ名門州立大学。歴史的な街並み、ブルーリッジ山脈、そしてワイン産地も魅力。"
    },
    "WA" => {
      name: "ワシントン州",
      english_name: "Washington",
      nickname: "エバーグリーンステート",
      capital: "オリンピア",
      largest_city: "シアトル",
      population: "約780万人",
      area: "184,661 km²",
      climate: "海洋性気候～半乾燥気候",
      average_temp: "年間平均気温：9-12°C",
      cost_of_living: "高い（全米平均の110-130%）",
      economy: "テクノロジー、航空宇宙、小売、農業、林業",
      famous_for: "Microsoft、Amazon、Boeing、スターバックス、シアトルの雨",
      education_highlights: "University of Washington、Washington State等",
      international_students: "世界トップクラスのテック企業との連携機会",
      job_opportunities: "テクノロジー、航空宇宙、クラウドコンピューティングで世界最高レベル",
      description: "シアトルを中心に世界を代表するテック企業が集結する「エバーグリーンステート」。Microsoft、Amazon、Boeing、Starbucksの本社があり、Google、Meta、Appleも大規模オフィスを構える。University of Washingtonはコンピュータサイエンスで全米トップ10に入る公立大学。州所得税がなく、テック企業での高収入を最大化できる。「雨の街シアトル」のイメージがあるが、実は霧雨が多いだけで年間降水量は全米平均程度。美しいピュージェット湾とカスケード山脈に囲まれた自然環境も魅力。"
    },
    "WV" => {
      name: "ウェストバージニア州",
      english_name: "West Virginia",
      nickname: "マウンテンステート",
      capital: "チャールストン",
      largest_city: "チャールストン",
      population: "約180万人",
      area: "62,756 km²",
      climate: "湿潤大陸性気候",
      average_temp: "年間平均気温：10-14°C",
      cost_of_living: "非常に低い（全米平均の80-85%）",
      economy: "エネルギー（石炭・天然ガス）、化学、製造業、観光",
      famous_for: "アパラチア山脈、カントリーロード、アウトドア活動",
      education_highlights: "West Virginia University等",
      international_students: "非常に手頃な学費と自然豊かな環境",
      job_opportunities: "エネルギー、ヘルスケア、製造業分野",
      description: "ジョン・デンバーの「カントリー・ロード」で歌われた、アパラチア山脈の美しい山岳州。生活費は全米で最も低い水準にあり、留学費用を最小限に抑えたい学生に最適。ホワイトウォーターラフティング、ハイキング、スキーなどアウトドア活動が豊富。石炭産業で栄えた歴史を持ち、現在はクリーンエネルギーへの転換を進めている。小規模で温かいコミュニティと、手つかずの自然が魅力。"
    },
    "WI" => {
      name: "ウィスコンシン州",
      english_name: "Wisconsin",
      nickname: "バジャーステート",
      capital: "マディソン",
      largest_city: "ミルウォーキー",
      population: "約590万人",
      area: "169,635 km²",
      climate: "湿潤大陸性気候",
      average_temp: "年間平均気温：5-9°C",
      cost_of_living: "中程度（全米平均の90-100%）",
      economy: "製造業、農業（酪農）、ヘルスケア、テクノロジー",
      famous_for: "チーズ、ビール、グリーンベイ・パッカーズ、酪農",
      education_highlights: "University of Wisconsin-Madison等の優秀な州立大学",
      international_students: "質の高い教育と中西部のフレンドリーな環境",
      job_opportunities: "製造業、ヘルスケア、農業テクノロジー分野",
      description: "「アメリカのデアリーランド（酪農地帯）」として知られ、チーズ生産量は全米の約25%を占める。ビール醸造の歴史も深く、ミラーやパブストの発祥地。University of Wisconsin-Madisonは研究型州立大学のトップ校の一つで、特に生命科学、社会科学で高い評価を得ている。マディソンは「アメリカで最も住みやすい都市」の常連で、活気ある学生街と美しい湖が魅力。NFLパッカーズの熱狂的なファンダムも独特の文化。"
    },
    "WY" => {
      name: "ワイオミング州",
      english_name: "Wyoming",
      nickname: "イコーリティステート",
      capital: "シャイアン",
      largest_city: "シャイアン",
      population: "約58万人",
      area: "253,335 km²",
      climate: "半乾燥気候",
      average_temp: "年間平均気温：4-8°C",
      cost_of_living: "中程度（全米平均の95-100%）",
      economy: "鉱業（石炭・天然ガス）、観光、農業",
      famous_for: "イエローストーン国立公園、グランドティトン、カウボーイ文化",
      education_highlights: "University of Wyoming",
      international_students: "小規模コミュニティと壮大な自然環境",
      job_opportunities: "エネルギー、観光、環境科学分野",
      description: "全米で最も人口が少ない州だが、世界初の国立公園イエローストーンとグランドティトンという壮大な自然遺産を持つ。州所得税がなく、鉱業からの収入で州財政は安定。女性に初めて参政権を認めた「イコーリティステート」としての歴史も持つ。University of Wyomingは州唯一の4年制大学で、地質学や環境科学の研究が盛ん。人口密度が低く、広大な草原と山岳地帯での静かな学習環境を求める学生に向いている。"
    },
    "DC" => {
      name: "ワシントンD.C.",
      english_name: "Washington, D.C.",
      nickname: "ザ・ディストリクト",
      capital: "—",
      largest_city: "—",
      population: "約69万人",
      area: "177 km²",
      climate: "湿潤亜熱帯気候",
      average_temp: "年間平均気温：12-15°C",
      cost_of_living: "非常に高い（全米平均の140-160%）",
      economy: "連邦政府、国際機関、法律、コンサルティング、テクノロジー",
      famous_for: "ホワイトハウス、国会議事堂、スミソニアン博物館群、リンカーン記念堂",
      education_highlights: "Georgetown、George Washington、Howard等の名門校",
      international_students: "政治・国際関係を学ぶには世界最高の環境",
      job_opportunities: "政府、国際機関、法律、コンサルティング、シンクタンクで無限の機会",
      description: "アメリカ合衆国の首都であり、州ではなく連邦直轄地区。ホワイトハウス、国会議事堂、最高裁判所の三権が集まる政治の中心地で、世界銀行やIMFなど国際機関、無数のシンクタンク、大使館が集結。政治学、国際関係、法学、公共政策を学ぶには世界最高の環境。Georgetown Universityの外交大学院は政界への登竜門として知られる。スミソニアン博物館群はすべて無料で、文化的資源も豊富。生活費は高いが、インターンシップやネットワーキングの機会は比類なし。"
    }
  }.freeze
end
